version: '3'

services:
  backend:
    container_name: backend
    build: ../suricator-backend
    volumes:
      - ../suricator-backend:/backend
    ports:
      - 3333:3333
    env_file:
      - ../suricator-backend/.env
    depends_on:
      - nlp
      - database

  web:
    container_name: web
    build: ../suricator-nuxt/
    volumes:
      - ../suricator-nuxt:/web
    ports:
      - '3000:3000'
    environment:
      HOST: 0.0.0.0
    depends_on:
      - backend

  nlp:
    container_name: nlp
    build: ../suricator-nlp
    ports:
      - 5000:5000

  database:
    container_name: database
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
